{% set name = "result" %}
{% set version = "0.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/result-{{ version }}.tar.gz
  sha256: 2ae9a2786c2cc3e9a2ce18e01a7a72c53294db773f30c5a7d944704e02a04db7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - result
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rustedpy/result
  summary: A Rust-like result type for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ruben-arts
