{% set name = "result" %}
{% set version = "0.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/result-{{ version }}.tar.gz
  sha256: 28bc217336c2f1d339b494241ccf3714e36e6bd90abc04df318d65dccb61594f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - result
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rustedpy/result
  summary: A Rust-like result type for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ruben-arts
